services:
  db:
    image: mariadb:10.6.4-focal
    command: '--default-authentication-plugin=mysql_native_password'
    restart: always
    volumes:
      - db-data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=spy
      - MYSQL_ROOT_PASSWORD=secret
    ports:
      - 3306:3306
volumes:
  db-data:
